--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ShockedPlot7560/FactionMaster
build-by-default: true
branches:
- master
projects:
  FactionMaster:
    path: ""
    icon: "icon.png"
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
    - src: CortexPE/Commando/Commando
      version: ^2.1.1
...
