--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ShockedPlot7560/FactionMaster
build-by-default: true
branches:
- stable
- dev
- pmmp4
projects:
  FactionMaster:
    path: ""
    icon: "icon.png"
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
    - src: CortexPE/Commando/Commando
      version: ^2.1.1
    - src: ifera-mc/UpdateNotifier/UpdateNotifier
      version: ^2.1.0
    - src: ifera-mc/ConfigUpdater/ConfigUpdater
      version: ^1.2.0
    - src: muqsit/simplepackethandler
      version: ^0.0.1
...
