name: FactionMaster
author: ShockedPlot7560
version: 2.0.0-alpha
api: 3.17.7
main: ShockedPlot7560\FactionMaster\Main
description: "Full configurable and modulable faction plugin"
virions: ["Commando", "libFormAPI"]