name: FactionMaster
author: ShockedPlot7560
version: 3.0.0-dev1
api: 3.17.7
main: ShockedPlot7560\FactionMaster\Main
description: "Full configurable and modulable faction plugin"
softdepend: ["ScoreHud"]
virions: ["Commando", "libFormAPI"]

permissions:
  factionmaster.scoreboard.place:
    description: "Allow the player to place scoreboard"
    default: "op"