name: Generation translation interface
on: 
  push:
  pull_request:

jobs:
  translation-interface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Composer dependencies
        run: |
          cd build && composer require pocketmine/pocketmine-mp && cd ../
      - name: Generate interface
        run: php build/generate-translation-interface.php